
package com.owl_ontologies.ecsdiservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Asseguradora1PortType", targetNamespace = "http://www.owl-ontologies.com/ECSDIServices")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public class Asseguradora1PortType {

    private AsseguradoraImpl implementacio = new AsseguradoraImpl();

    /**
     * 
     * @param inputRestriccions
     * @param inputPacientAutoritzacio
     * @param inputAccioAutoritzacio
     * @return
     *     returns com.owl_ontologies.ecsdiservices.ConjuntCentresType
     */
    @WebMethod(operationName = "LlistaCentresDeSalut")
    @WebResult(name = "OutputCentresAutoritzats", partName = "OutputCentresAutoritzats")
    public ConjuntCentresType llistaCentresDeSalut(
        @WebParam(name = "InputAccioAutoritzacio", partName = "InputAccioAutoritzacio")
        String inputAccioAutoritzacio,
        @WebParam(name = "InputPacientAutoritzacio", partName = "InputPacientAutoritzacio")
        PacientType inputPacientAutoritzacio,
        @WebParam(name = "InputRestriccions", partName = "InputRestriccions")
        ConjuntRestriccionsType inputRestriccions) {
        return implementacio.llistaCentresDeSalut(inputRestriccions, 
                inputPacientAutoritzacio, inputAccioAutoritzacio);
    }

}
