
package com.owl_ontologies.ecsdiservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Centre1PortType", targetNamespace = "http://www.owl-ontologies.com/ECSDIServices")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public class Centre1PortType {


    /**
     * 
     * @param citaObtenirResultatsCitaCentre1
     * @return
     *     returns com.owl_ontologies.ecsdiservices.ConjuntResultatsType
     */
    @WebMethod(operationName = "ObtenirResultatsCita")
    @WebResult(name = "resultatsCentre1", partName = "resultatsCentre1")
    public ConjuntResultatsType obtenirResultatsCita(
        @WebParam(name = "citaObtenirResultatsCitaCentre1", partName = "citaObtenirResultatsCitaCentre1")
        CitaType citaObtenirResultatsCitaCentre1) {
        CentreImpl implementacio = new CentreImpl();
        return implementacio.obtenirResultatsCita(citaObtenirResultatsCitaCentre1);
    }

    /**
     * 
     * @param tipusProvaAnalisi
     * @param restriccionsAnalisi
     * @return
     *     returns com.owl_ontologies.ecsdiservices.ConjuntOfertesType
     */
    @WebMethod(operationName = "DemanarDisponibilitat")
    @WebResult(name = "ofertesAnalisi", partName = "ofertesAnalisi")
    public ConjuntOfertesType demanarDisponibilitat(
        @WebParam(name = "tipusProvaAnalisi", partName = "tipusProvaAnalisi")
        AnalisiType tipusProvaAnalisi,
        @WebParam(name = "restriccionsAnalisi", partName = "restriccionsAnalisi")
        ConjuntRestriccionsType restriccionsAnalisi) {
        CentreImpl implementacio = new CentreImpl();
        return implementacio.demanarDisponibilitat(tipusProvaAnalisi, restriccionsAnalisi);
    }

}
