
package com.owl_ontologies.ecsdiservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Centre5PortType", targetNamespace = "http://www.owl-ontologies.com/ECSDIServices")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public class Centre5PortType {


    /**
     * 
     * @param tipusMetgeEspecialistaAnestesista
     * @param restriccionsMetgeEspecialistaAnestesista
     * @return
     *     returns com.owl_ontologies.ecsdiservices.ConjuntOfertesType
     */
    @WebMethod(operationName = "DemanarDisponibilitat")
    @WebResult(name = "ofertesMetgeEspecialistaAnestesista", partName = "ofertesMetgeEspecialistaAnestesista")
    public ConjuntOfertesType demanarDisponibilitat(
        @WebParam(name = "tipusMetgeEspecialistaAnestesista", partName = "tipusMetgeEspecialistaAnestesista")
        VisitaMedicaEspecialistaAnestesistaType tipusMetgeEspecialistaAnestesista,
        @WebParam(name = "restriccionsMetgeEspecialistaAnestesista", partName = "restriccionsMetgeEspecialistaAnestesista")
        ConjuntRestriccionsType restriccionsMetgeEspecialistaAnestesista) {
        CentreImpl implementacio = new CentreImpl();
        return implementacio.demanarDisponibilitat(implementacio, restriccionsMetgeEspecialistaAnestesista);
    }

}
