
package com.owl_ontologies.ecsdiservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Centre2PortType", targetNamespace = "http://www.owl-ontologies.com/ECSDIServices")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public class Centre2PortType {


    /**
     * 
     * @param citaObtenirResultatsCitaCentre2
     * @return
     *     returns com.owl_ontologies.ecsdiservices.ConjuntResultatsType
     */
    @WebMethod(operationName = "ObtenirResultatsCita")
    @WebResult(name = "resultatsCentre2", partName = "resultatsCentre2")
    public ConjuntResultatsType obtenirResultatsCita(
        @WebParam(name = "citaObtenirResultatsCitaCentre2", partName = "citaObtenirResultatsCitaCentre2")
        CitaType citaObtenirResultatsCitaCentre2) {
        CentreImpl implementacio = new CentreImpl();
        return implementacio.obtenirResultatsCita(citaObtenirResultatsCitaCentre2);
    }

    /**
     * 
     * @param restriccionsAnalisiOrina
     * @param tipusProvaAnalisiOrina
     * @return
     *     returns com.owl_ontologies.ecsdiservices.ConjuntOfertesType
     */
    @WebMethod(operationName = "DemanarDisponibilitat")
    @WebResult(name = "ofertesAnalisiOrina", partName = "ofertesAnalisiOrina")
    public ConjuntOfertesType demanarDisponibilitat(
        @WebParam(name = "restriccionsAnalisiOrina", partName = "restriccionsAnalisiOrina")
        ConjuntRestriccionsType restriccionsAnalisiOrina,
        @WebParam(name = "tipusProvaAnalisiOrina", partName = "tipusProvaAnalisiOrina")
        AnalisiDeOrinaType tipusProvaAnalisiOrina) {
        CentreImpl implementacio = new CentreImpl();
        return implementacio.demanarDisponibilitat(tipusProvaAnalisiOrina, restriccionsAnalisiOrina);
    }

}
