
package com.owl_ontologies.ecsdiservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReservesPortType", targetNamespace = "http://www.owl-ontologies.com/ECSDIServices")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public class ReservesPortType {


    /**
     * 
     * @param pacientReserva
     * @param ofertaReserva
     * @return
     *     returns com.owl_ontologies.ecsdiservices.CitaType
     */
    @WebMethod(operationName = "ReservaVisita")
    @WebResult(name = "citaReserva", partName = "citaReserva")
    public CitaType reservaVisita(
        @WebParam(name = "pacientReserva", partName = "pacientReserva")
        PacientType pacientReserva,
        @WebParam(name = "ofertaReserva", partName = "ofertaReserva")
        OfertaType ofertaReserva) {
        CitaType cita = new CitaType();
        //cita.estatCita = EstatCitaType.CONCERTADA;
        cita.perRealitzar = ofertaReserva.esPerUna;
        cita.teLlocA = ofertaReserva.pertanyAUn;
        if ((ofertaReserva.estaDisponibleEn != null) && 
                (ofertaReserva.estaDisponibleEn.conteFranjes != null) &&
                !ofertaReserva.estaDisponibleEn.conteFranjes.isEmpty())
            cita.teLlocEn = ofertaReserva.estaDisponibleEn.conteFranjes.get(0);
        return cita;
    }

}
